apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: WORKSHOP
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Aw3s0m3
  PGDATA: /var/lib/postgresql/data/pgdata
